// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhXvcVZjxdTwCMLX1zbms5L_rY_wD7-w',
    appId: '1:220328963165:web:033599298e7c71997fb1b4',
    messagingSenderId: '220328963165',
    projectId: 'nnbk-230cb',
    authDomain: 'nnbk-230cb.firebaseapp.com',
    storageBucket: 'nnbk-230cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAN4Bu2bsucCdPNzEk2jH7sNG1ivvomE',
    appId: '1:220328963165:android:d3bbfb1d8148fbec7fb1b4',
    messagingSenderId: '220328963165',
    projectId: 'nnbk-230cb',
    storageBucket: 'nnbk-230cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeEETzFRQ4or4M3GSMXixjV-lQ1on8Uf0',
    appId: '1:220328963165:ios:8b0d7aa8a96da53c7fb1b4',
    messagingSenderId: '220328963165',
    projectId: 'nnbk-230cb',
    storageBucket: 'nnbk-230cb.appspot.com',
    iosBundleId: 'com.example.votDapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeEETzFRQ4or4M3GSMXixjV-lQ1on8Uf0',
    appId: '1:220328963165:ios:8b0d7aa8a96da53c7fb1b4',
    messagingSenderId: '220328963165',
    projectId: 'nnbk-230cb',
    storageBucket: 'nnbk-230cb.appspot.com',
    iosBundleId: 'com.example.votDapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAhXvcVZjxdTwCMLX1zbms5L_rY_wD7-w',
    appId: '1:220328963165:web:be331a0dfa139fe87fb1b4',
    messagingSenderId: '220328963165',
    projectId: 'nnbk-230cb',
    authDomain: 'nnbk-230cb.firebaseapp.com',
    storageBucket: 'nnbk-230cb.appspot.com',
  );

}